#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON1                               102
#define IDI_ICON_SPOIT                          103
#define IDD_SETTINGSDIALOG                      104
#define IDD_GENERALTAB                          105
#define IDD_DESIGNTAB                           107
#define IDD_VERSIONTAB                          108
#define IDR_TRAYMENU                            110
#define IDI_ICON_DISABLE                        111
#define IDD_SHOWWINDOWTAB                       113
#define IDR_SHORTCUTKEY                         115
#define IDD_SHORTCUTKEYTAB                      118
#define IDD_MOUSETAB                            120
#define IDR_SELECTMENU                          122
#define IDR_INCREMENTALSEARCHMENU               125
#define IDR_WINDOWMENU                          127
#define IDR_PROCESSMENU                         129
#define IDR_MAINMENU                            131
#define IDR_COPYINFOMENU                        133
#define IDD_ADVANCEDTAB                         136
#define IDR_OPACITYMENU                         137
#define IDD_COMMANDTAB                          138
#define IDR_CMDPARAMETERSMENU                   139
#define IDR_COMMANDMENU                         140
#define IDI_CURSOR_BLANK                        142
#define IDC_BUTTON_UNREGHOTKEY                  1000
#define IDC_TAB1                                1002
#define IDC_STATIC_ALPHA                        1005
#define IDC_CHECKBOX_SELECTSECONDWINDOW         1007
#define IDC_SLIDER_ALPHA                        1008
#define IDC_CHECKBOX_DESKTOPITEM                1012
#define IDC_HOTKEY_DISPLAY                      1015
#define IDC_CHECKBOX_AUTOSTART                  1019
#define IDC_CHECKBOX_LEFTTOP                    1020
#define IDC_CHECKBOX_LEFTBOTTOM                 1022
#define IDC_CHECKBOX_CANCELITEM                 1023
#define IDC_CHECKBOX_RIGHTTOP                   1024
#define IDC_CHECKBOX_RIGHTBOTTOM                1025
#define IDC_EDIT_TEXTCOLOR                      1038
#define IDC_EDIT_TEXTBKCOLOR                    1039
#define IDC_BUTTON_TEXTCOLOR                    1040
#define IDC_BUTTON_TEXTBKCOLOR                  1041
#define IDC_COMBO_FONTSIZE                      1042
#define IDC_COMBO_FONT                          1043
#define IDC_CHECKBOX_BOLD                       1044
#define IDC_CHECKBOX_ITALIC                     1045
#define IDC_CHECKBOX_UNDERLINE                  1046
#define IDC_CHECKBOX_STRIKEOUT                  1047
#define IDC_LIST_PREVIEW                        1048
#define IDC_STATIC_URL                          1049
#define IDC_STATIC_VERSION                      1050
#define IDC_BUTTON_CMDREMOVE                    40000
#define IDC_COMBO_THUMBNAIL_VERTICALALIGN       40000
#define IDC_PICTURE_DESKTOP                     40000
#define IDS_URL                                 40000
#define IDC_CHECKBOX_HOTKEY_MOVECURSORSELECTEDWINDOW 40001
#define IDC_CHECKBOX_RUN_AS_ADMINISTRATOR       40001
#define IDC_COMBO_THUMBNAIL                     40001
#define IDS_FILENAME                            40001
#define IDC_CHECKBOX_THUMBNAIL_ORIGINAL         40002
#define IDC_EDIT_SHOWWINDOW_CURSORCORNER_DELAY  40002
#define IDC_BUTTON_DEFAULT                      40003
#define IDC_COMBO_HOTKEY_CURSOR                 40003
#define IDC_COMBO_MULTIMONITOR_MODE             40003
#define IDC_CHECKBOX_MOUSE_MOVECURSORSELECTEDWINDOW 40004
#define IDC_CHECKBOX_ONLY_ACTIVEVIRTUALDESKTOP  40004
#define IDC_CHECKBOX_DRAG_MOUSEHOVER            40005
#define IDC_CHECKBOX_MOUSE_EACH_MONITOR         40005
#define IDC_CHECKBOX_LEFT                       40006
#define IDC_CHECKBOX_ONLY_ACTIVEMONITOR         40006
#define IDC_CHECKBOX_SHOW_MOVECURSORATSTART     40007
#define IDC_CHECKBOX_THUMBNAIL                  40007
#define IDC_CHECKBOX_DISABLEDOUBLECLICK         40008
#define IDC_CHECKBOX_DRAG_TIMEOUT               40009
#define IDC_CHECKBOX_TOP                        40010
#define IDC_EDIT_XOFFSET                        40011
#define IDC_CHECKBOX_RIGHT                      40014
#define IDC_COMBO_CMDNO                         40015
#define IDC_LISTVIEW_MOUSE                      40016
#define IDC_SPIN_XOFFSET                        40017
#define IDC_CHECKBOX_BOTTOM                     40018
#define IDC_EDIT_CMDNAME                        40020
#define IDC_SPIN_YOFFSET                        40021
#define IDC_CHECKBOX_SHOW_MOUSEWHEEL            40022
#define IDC_COMBO_CMDMODE                       40023
#define IDC_EDIT_TIMEOUT                        40024
#define IDC_EDIT_YOFFSET                        40025
#define IDC_EDIT_CMDPARAMETERS                  40026
#define IDC_STATIC_HOTKEY_SHIFT                 40028
#define IDC_COMBO_MIGEMO                        40029
#define IDC_LISTVIEW_COMMAND                    40031
#define IDC_STATIC_HOTKEY_ALT                   40032
#define IDC_COMBO_MOUSE                         40034
#define IDC_EDIT_CMDFILEPATH                    40035
#define IDC_EDIT_THUMBNAIL_DELAY                40036
#define IDC_BUTTON_CMDSAVE                      40037
#define IDC_EDIT_BACKGROUND                     40038
#define IDC_EDIT_EXCLUDE_FILENAME               40039
#define IDC_STATIC_HOTKEY_WIN                   40040
#define IDC_COMBO_CMDOPTION                     40041
#define IDC_EDIT_THUMBNAIL_SIZE                 40042
#define IDC_LISTVIEW_SHORTCUTKEY                40043
#define IDC_STATIC_HOTKEY_CTRL                  40044
#define IDC_BUTTON_CMDPARAMETERS                40045
#define IDC_PICTURE_ICON                        40046
#define IDC_COMBO_CMDSHOW                       40047
#define IDM_KEY_FLEX_MATCH                      40048
#define IDM_KEY_UNIQUE_WINDOW                   40049
#define IDM_KEY_SEARCHSCOPE                     40050
#define IDM_KEY_BSSTRING                        40051
#define IDC_BUTTON_CMDWORKINGDIRECTORY          40052
#define IDM_KEY_COPY_NAME                       40053
#define IDC_EDIT_CMDWORKINGDIRECTORY            40054
#define IDC_BUTTON_BACKGROUND                   40055
#define IDC_BUTTON_CMDFILEPATH                  40056
#define IDC_CHECKBOX_HOTKEY                     40057
#define IDM_KEY_RESET                           40058
#define IDC_BUTTON_SAVEMOUSE                    40059
#define IDC_CHECKBOX_MIGEMO_CASESENSITIVE       40060
#define IDM_KEY_COPY_TITLE                      40061
#define IDC_BUTTON_REMOVEMOUSE                  40062
#define IDC_COMBO_ICON                          40063
#define IDM_KEY_COPYINFOMENU                    40064
#define IDC_COMBO_MOUSE_CMD                     40065
#define IDC_EDIT_FILENAME                       40066
#define IDC_HOTKEY_SHORTCUTKEY                  40067
#define IDC_SLIDER_BG_ALPHA                     40068
#define IDM_KEY_INFO                            40069
#define IDC_SPIN_FILENAME                       40070
#define IDM_KEY_FORWARD_MATCH                   40071
#define IDC_EDIT_WINDOWTITLE                    40072
#define IDM_KEY_COPY_COMMANDLINE                40073
#define IDC_SPIN_WINDOWTITLE                    40074
#define IDC_STATIC_BG_ALPHA                     40075
#define IDM_KEY_PREV                            40076
#define IDC_BUTTON_REMOVEKEY                    40077
#define IDC_CHECKBOX_MOUSEHOVER                 40078
#define IDC_SLIDER_RESIZEPERCENT                40079
#define IDM_KEY_TERMINATETREE                   40080
#define IDC_CHECKBOX_TIMEOUT                    40081
#define IDC_STATIC_RESIZEPERCENT                40082
#define IDM_KEY_PARTIAL_MATCH                   40083
#define IDC_BUTTON_SAVEKEY                      40084
#define IDM_KEY_MOVE                            40085
#define IDC_PICTURE_TEXTBKCOLOR                 40086
#define IDC_PICTURE_TEXTCOLOR                   40088
#define IDM_MENU_SETTINGS                       40089
#define IDC_BUTTON_SELECTED                     40090
#define IDC_COMBO_SHORTCUTKEY                   40091
#define IDM_KEY_NEXT                            40092
#define IDM_MENU_DISABLE                        40093
#define IDC_COMBO_SEARCH                        40094
#define IDM_KEY_TOPMOST                         40095
#define IDC_CHECKBOX_ENTERUNIQUEWINDOW          40096
#define IDM_KEY_RESTORE                         40097
#define IDM_MENU_VERSION                        40098
#define IDM_KEY_SWITCH                          40099
#define IDM_KEY_CANCEL                          40100
#define IDM_MENU_EXIT                           40101
#define IDM_KEY_SWAP                            40102
#define IDM_MENU_SHOW                           40103
#define IDC_CHECKBOX_MOUSEOUT                   40104
#define IDM_KEY_QUIT                            40105
#define IDC_CHECKBOX_FIRSTCOLUMNONLY            40106
#define IDM_KEY_FIRST                           40107
#define IDM_KEY_LAST                            40108
#define IDM_KEY_MINIMIZE                        40109
#define IDM_KEY_MAXIMIZE                        40110
#define IDM_KEY_CLOSE                           40111
#define IDM_KEY_BS_STRING                       40112
#define IDM_KEY_SETTINGS                        40113
#define IDM_KEY_DESKTOP                         40114
#define IDM_KEY_TERMINATE                       40115
#define IDM_KEY_IDLE_PRIORITY                   40116
#define IDM_KEY_BELOW_NORMAL_PRIORITY           40117
#define IDM_KEY_NORMAL_PRIORITY                 40118
#define IDM_KEY_ABOVE_NORMAL_PRIORITY           40119
#define IDM_KEY_HIGH_PRIORITY                   40120
#define IDM_KEY_REALTIME_PRIORITY               40121
#define IDM_KEY_MENU                            40122
#define IDM_KEY_SELECTMENU                      40123
#define IDM_KEY_INCREMENTALSEARCHMENU           40124
#define IDM_KEY_WINDOWMENU                      40125
#define IDM_KEY_PROCESSMENU                     40126
#define IDM_KEY_CHILDPROCESS                    40127
#define IDM_KEY_SIZE                            40128
#define IDM_KEY_THUMBNAIL                       40129
#define IDM_KEY_THUMBNAIL_ORIGINAL              40130
#define IDM_KEY_CENTERCURSOR                    40131
#define IDM_KEY_MOVETOACTIVEMONITOR             40132
#define IDM_KEY_MOVETOMONITOR                   40133
#define IDM_KEY_CENTER                          40134
#define IDM_KEY_OPACITY0                        40135
#define IDM_KEY_OPACITY10                       40136
#define IDM_KEY_OPACITY20                       40137
#define IDM_KEY_OPACITY30                       40138
#define IDM_KEY_OPACITY40                       40139
#define IDM_KEY_OPACITY50                       40140
#define IDM_KEY_OPACITY60                       40141
#define IDM_KEY_OPACITY70                       40142
#define IDM_KEY_OPACITY80                       40143
#define IDM_KEY_OPACITY90                       40144
#define IDM_KEY_OPACITY100                      40145
#define IDM_KEY_OPACITYTOGGLE                   40146
#define IDM_KEY_OPACITYMENU                     40147
#define IDM_KEY_BACKGROUND                      40148
#define IDM_KEY_COMMAND_FULLPATH                40149
#define IDM_KEY_COMMAND_DIRECTORY               40150
#define IDM_KEY_COMMAND_FILENAME                40151
#define IDM_KEY_COMMAND_TITLE                   40152
#define IDM_KEY_COMMAND_HANDLE                  40153
#define IDM_KEY_COMMAND_PERCENT                 40154
#define IDM_KEY_COMMAND_HANDLEX                 40155
#define IDM_KEY_COMMAND_CLASS                   40156
#define IDM_KEY_COMMANDMENU                     40157
#define IDM_KEY_COMMAND1                        40158
#define IDM_KEY_COMMAND2                        40159
#define IDM_KEY_COMMAND3                        40160
#define IDM_KEY_COMMAND4                        40161
#define IDM_KEY_COMMAND5                        40162
#define IDM_KEY_COMMAND6                        40163
#define IDM_KEY_COMMAND7                        40164
#define IDM_KEY_COMMAND8                        40165
#define IDM_KEY_COMMAND9                        40166
#define IDM_KEY_COMMAND10                       40167
#define IDM_KEY_COMMAND11                       40168
#define IDM_KEY_COMMAND12                       40169
#define IDM_KEY_COMMAND13                       40170
#define IDM_KEY_COMMAND14                       40171
#define IDM_KEY_COMMAND15                       40172
#define IDM_KEY_COMMAND16                       40173
#define IDM_KEY_COMMAND17                       40174
#define IDM_KEY_COMMAND18                       40175
#define IDM_KEY_COMMAND19                       40176
#define IDM_KEY_COMMAND20                       40177
#define IDM_KEY_COMMAND21                       40178
#define IDM_KEY_COMMAND22                       40179
#define IDM_KEY_COMMAND23                       40180
#define IDM_KEY_COMMAND24                       40181
#define IDM_KEY_COMMAND25                       40182
#define IDM_KEY_COMMAND26                       40183
#define IDM_KEY_COMMAND27                       40184
#define IDM_KEY_COMMAND28                       40185
#define IDM_KEY_COMMAND29                       40186
#define IDM_KEY_COMMAND30                       40187
#define IDM_KEY_COMMAND31                       40188
#define IDM_KEY_COMMAND32                       40189
#define IDM_KEY_COMMAND33                       40190
#define IDM_KEY_COMMAND34                       40191
#define IDM_KEY_COMMAND35                       40192
#define IDM_KEY_COMMAND36                       40193
#define IDM_KEY_COMMAND37                       40194
#define IDM_KEY_COMMAND38                       40195
#define IDM_KEY_COMMAND39                       40196
#define IDM_KEY_COMMAND40                       40197
#define IDM_KEY_COMMAND41                       40198
#define IDM_KEY_COMMAND42                       40199
#define IDM_KEY_COMMAND43                       40200
#define IDM_KEY_COMMAND44                       40201
#define IDM_KEY_COMMAND45                       40202
#define IDM_KEY_COMMAND46                       40203
#define IDM_KEY_COMMAND47                       40204
#define IDM_KEY_COMMAND48                       40205
#define IDM_KEY_COMMAND49                       40206
#define IDM_KEY_COMMAND50                       40207
