#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON1                               102
#define IDI_ICON_SPOIT                          103
#define IDD_SETTINGSDIALOG                      104
#define IDD_GENERALTAB                          105
#define IDD_DESIGNTAB                           107
#define IDD_VERSIONTAB                          108
#define IDR_TRAYMENU                            110
#define IDI_ICON_DISABLE                        111
#define IDD_SHOWWINDOWTAB                       113
#define IDR_SHORTCUTKEY                         115
#define IDD_SHORTCUTKEYTAB                      118
#define IDD_MOUSETAB                            120
#define IDR_SELECTMENU                          122
#define IDR_INCREMENTALSEARCHMENU               125
#define IDR_WINDOWMENU                          127
#define IDR_PROCESSMENU                         129
#define IDR_MAINMENU                            131
#define IDR_COPYINFOMENU                        133
#define IDC_BUTTON_UNREGHOTKEY                  1000
#define IDC_CHECKBOX_TASKBAREQUIVALENT          1001
#define IDC_TAB1                                1002
#define IDC_STATIC_ALPHA                        1005
#define IDC_CHECKBOX_SELECTSECONDWINDOW         1007
#define IDC_SLIDER_ALPHA                        1008
#define IDC_CHECKBOX_DESKTOPITEM                1012
#define IDC_HOTKEY_DISPLAY                      1015
#define IDC_CHECKBOX_AUTOSTART                  1019
#define IDC_CHECKBOX_LEFTTOP                    1020
#define IDC_CHECKBOX_LEFTBOTTOM                 1022
#define IDC_CHECKBOX_CANCELITEM                 1023
#define IDC_CHECKBOX_RIGHTTOP                   1024
#define IDC_CHECKBOX_RIGHTBOTTOM                1025
#define IDC_EDIT_TEXTCOLOR                      1038
#define IDC_EDIT_TEXTBKCOLOR                    1039
#define IDC_BUTTON_TEXTCOLOR                    1040
#define IDC_BUTTON_TEXTBKCOLOR                  1041
#define IDC_COMBO_FONTSIZE                      1042
#define IDC_COMBO_FONT                          1043
#define IDC_CHECKBOX_BOLD                       1044
#define IDC_CHECKBOX_ITALIC                     1045
#define IDC_CHECKBOX_UNDERLINE                  1046
#define IDC_CHECKBOX_STRIKEOUT                  1047
#define IDC_LIST_PREVIEW                        1048
#define IDC_STATIC_URL                          1049
#define IDC_STATIC_VERSION                      1050
#define IDC_BUTTON_DEFAULT                      40000
#define IDM_KEY_FLEX_MATCH                      40000
#define IDS_URL                                 40000
#define IDC_CHECKBOX_DISABLEDOUBLECLICK         40001
#define IDC_EDIT_XOFFSET                        40001
#define IDM_KEY_UNIQUE_WINDOW                   40001
#define IDS_FILENAME                            40001
#define IDC_LISTVIEW_MOUSE                      40002
#define IDC_SPIN_XOFFSET                        40002
#define IDC_SPIN_YOFFSET                        40003
#define IDC_EDIT_YOFFSET                        40004
#define IDM_KEY_SEARCHSCOPE                     40004
#define IDC_COMBO_MIGEMO                        40006
#define IDC_COMBO_MOUSE                         40007
#define IDC_EDIT_BACKGROUND                     40008
#define IDC_LISTVIEW_SHORTCUTKEY                40009
#define IDC_PICTURE_ICON                        40010
#define IDM_KEY_BSSTRING                        40011
#define IDM_KEY_COPY_NAME                       40012
#define IDC_BUTTON_BACKGROUND                   40014
#define IDC_CHECKBOX_HOTKEY                     40015
#define IDM_KEY_RESET                           40016
#define IDC_BUTTON_SAVEMOUSE                    40017
#define IDC_CHECKBOX_MIGEMO_CASESENSITIVE       40018
#define IDM_KEY_COPY_TITLE                      40020
#define IDC_BUTTON_REMOVEMOUSE                  40021
#define IDC_COMBO_ICON                          40022
#define IDM_KEY_COPYINFOMENU                    40024
#define IDC_COMBO_MOUSE_CMD                     40025
#define IDC_EDIT_FILENAME                       40026
#define IDC_HOTKEY_SHORTCUTKEY                  40027
#define IDC_SLIDER_BG_ALPHA                     40028
#define IDM_KEY_INFO                            40029
#define IDC_SPIN_FILENAME                       40030
#define IDM_KEY_FORWARD_MATCH                   40032
#define IDC_EDIT_WINDOWTITLE                    40033
#define IDM_KEY_COPY_COMMANDLINE                40035
#define IDC_SPIN_WINDOWTITLE                    40036
#define IDC_STATIC_BG_ALPHA                     40037
#define IDM_KEY_PREV                            40038
#define IDC_BUTTON_REMOVEKEY                    40039
#define IDC_CHECKBOX_MOUSEHOVER                 40040
#define IDC_SLIDER_RESIZEPERCENT                40041
#define IDM_KEY_TERMINATETREE                   40042
#define IDC_CHECKBOX_TIMEOUT                    40043
#define IDC_STATIC_RESIZEPERCENT                40044
#define IDM_KEY_PARTIAL_MATCH                   40045
#define IDC_BUTTON_SAVEKEY                      40046
#define IDM_KEY_MOVE                            40047
#define IDC_PICTURE_TEXTBKCOLOR                 40048
#define IDM_KEY_AND                             40049
#define IDC_PICTURE_TEXTCOLOR                   40050
#define IDM_MENU_SETTINGS                       40052
#define IDC_BUTTON_SELECTED                     40053
#define IDC_COMBO_SHORTCUTKEY                   40055
#define IDM_KEY_NEXT                            40058
#define IDM_MENU_DISABLE                        40060
#define IDC_COMBO_SEARCH                        40061
#define IDM_KEY_TOPMOST                         40063
#define IDC_CHECKBOX_ENTERUNIQUEWINDOW          40064
#define IDM_KEY_RESTORE                         40066
#define IDM_MENU_VERSION                        40068
#define IDM_KEY_SWITCH                          40069
#define IDM_KEY_CANCEL                          40070
#define IDM_MENU_EXIT                           40071
#define IDM_KEY_SWAP                            40072
#define IDM_MENU_SHOW                           40073
#define IDC_CHECKBOX_MOUSEOUT                   40074
#define IDM_KEY_QUIT                            40075
#define IDC_CHECKBOX_FIRSTCOLUMNONLY            40076
#define IDM_KEY_FIRST                           40077
#define IDM_KEY_LAST                            40078
#define IDM_KEY_MINIMIZE                        40079
#define IDM_KEY_MAXIMIZE                        40080
#define IDM_KEY_CLOSE                           40081
#define IDM_KEY_BS_STRING                       40082
#define IDM_KEY_SETTINGS                        40083
#define IDM_KEY_DESKTOP                         40084
#define IDM_KEY_TERMINATE                       40085
#define IDM_KEY_IDLE_PRIORITY                   40086
#define IDM_KEY_BELOW_NORMAL_PRIORITY           40087
#define IDM_KEY_NORMAL_PRIORITY                 40088
#define IDM_KEY_ABOVE_NORMAL_PRIORITY           40089
#define IDM_KEY_HIGH_PRIORITY                   40090
#define IDM_KEY_REALTIME_PRIORITY               40091
#define IDM_KEY_MENU                            40092
#define IDM_KEY_SELECTMENU                      40093
#define IDM_KEY_INCREMENTALSEARCHMENU           40094
#define IDM_KEY_WINDOWMENU                      40095
#define IDM_KEY_PROCESSMENU                     40096
#define IDM_KEY_CHILDPROCESS                    40097
#define IDM_KEY_SIZE                            40098
